apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism-app
  namespace: photoprism
spec:
  chart:
    spec:
      chart: polymorphic-app
      reconcileStrategy: ChartVersion
      version: 1.2.8
      sourceRef:
        kind: HelmRepository
        name: polymorphic
        namespace: photoprism
  interval: 10m0s
  values:
    image:
      repository: photoprism/photoprism
      tag: "231128"
      pullPolicy: IfNotPresent
    env:
    - name: PHOTOPRISM_ADMIN_USER
      value: "admin"
    - name: PHOTOPRISM_ADMIN_PASSWORD
      value: "secure"
    - name:  PHOTOPRISM_AUTH_MODE
      value: "public"
    - name: PHOTOPRISM_SITE_URL
      value: "http://photoprism.me:2342/"
    - name: PHOTOPRISM_DATABASE_DRIVER
      value: "mysql"
    - name: PHOTOPRISM_DATABASE_SERVER
      value: "photoprism-mariadb.photoprism.svc.cluster.local:3306"
    - name: PHOTOPRISM_DATABASE_NAME
      value: "photoprism"
    - name: PHOTOPRISM_DATABASE_USER
      value: "photoprism"
    - name: PHOTOPRISM_DATABASE_PASSWORD
      value: "dlpFQUZPNG9mbDBxd0NSbUZV"
    - name: PHOTOPRISM_ORIGINALS_LIMIT
      value: "5000"
    - name: PHOTOPRISM_HTTP_COMPRESSION
      value: "gzip"
    - name: PHOTOPRISM_LOG_LEVEL
      value: "info"
    - name: PHOTOPRISM_READONLY
      value: "false"
    - name: PHOTOPRISM_EXPERIMENTAL
      value: "false"
    - name: PHOTOPRISM_DISABLE_CHOWN
      value: "false"
    - name: PHOTOPRISM_DISABLE_WEBDAV
      value: "false"
    - name: PHOTOPRISM_DISABLE_SETTINGS
      value: "false"
    - name: PHOTOPRISM_DISABLE_TENSORFLOW
      value: "false"
    - name: PHOTOPRISM_DISABLE_FACES
      value: "false"
    - name: PHOTOPRISM_DISABLE_CLASSIFICATION
      value: "false"
    - name: PHOTOPRISM_DISABLE_VECTORS
      value: "false"
    - name: PHOTOPRISM_DISABLE_RAW
      value: "false"
    - name: PHOTOPRISM_RAW_PRESETS
      value: "false"
    - name: PHOTOPRISM_JPEG_QUALITY
      value: "85"
    - name: PHOTOPRISM_DETECT_NSFW
      value: "false"
    - name: PHOTOPRISM_UPLOAD_NSFW
      value: "true"

    services:
    - name: photoprism-svc
      type: StatefulSet
      ports:
      - name: http
        containerPort: 2342
      healthcheck:
        enabled: false
      service:
        enabled: true
        ports:
        - port: 2342
          targetPort: http
          name: http
        securityContext:
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
          runAsGroup: 0
      # ingress:
      #   enabled: false
      #   className: "nginx"
      #   hosts:
      #     - host: photos.pride.improwised.dev
      #       paths:
      #       - path: /
      #         pathType: Prefix
      #         servicePort: 2342
      volumeMounts:
      - name: originals
        mountPath: /photoprism/originals
        # subPath: photos/family
      - name: storage
        mountPath: /photoprism/storage
      - name: imports
        mountPath: /photoprism/import
      # volumes:
      # - name: originals
      #   nfs:
      #     server: 10.0.1.9
      #     path: /share/CACHEDEV3_DATA/ServerStorage/Photos/media
      #     # readOnly: true     # PhotoPrism should not delete your originals, but just to be safe...
      # # Photoprism-only share for storing image thumbnails, etc.
      # - name: storage
      #   nfs:
      #     server: 10.0.1.9
      #     path: /share/CACHEDEV3_DATA/ServerStorage/Photos/photoprism
      # - name: imports
      #   nfs:
      #     server: 10.0.1.9
      #     path: /share/CACHEDEV3_DATA/ServerStorage/Photos/imports
      volumeClaimTemplates:
      - metadata:
          name: originals
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "local-path"
          resources:
            requests:
              storage: 1Gi
      - metadata:
          name: storage
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "local-path"
          resources:
            requests:
              storage: 1Gi
      - metadata:
          name: imports
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "local-path"
          resources:
            requests:
              storage: 1Gi