apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: resilio-sync
  namespace: photoprism
spec:
  chart:
    spec:
      chart: polymorphic-app
      reconcileStrategy: ChartVersion
      version: 1.2.8
      sourceRef:
        kind: HelmRepository
        name: polymorphic
        namespace: photoprism
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/linuxserver/resilio-sync
      tag: version-2.7.3.1381-1
      pullPolicy: IfNotPresent
    env:
    - name: TZ
      value: "UTC"
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: UMASK
      value: "null"

    services:
    - name: resilio-sync
      type: StatefulSet
      ports:
      - name: http
        containerPort: 8888
      healthcheck:
        enabled: false
      service:
        enabled: true
        ports:
        - port: 8888
          targetPort: http
          name: http
      ingress:
        enabled: true
        className: "nginx"
        hosts:
          - host: sync.pride.improwised.dev
            paths:
            - path: /
              pathType: Prefix
              servicePort: 8888
      volumeMounts:
      - name: sync
        mountPath: /sync
      - name: config
        mountPath: /config
      # volumes:
      # - name: sync
      #   nfs:
      #     server: 10.0.1.9
      #     path: /share/CACHEDEV3_DATA/ServerStorage/Photos/imports/sync
      # volumeClaimTemplates:
      # - metadata:
      #     name: config
      #   spec:
      #     accessModes: [ "ReadWriteOnce" ]
      #     storageClassName: "longhorn"
      #     resources:
      #       requests:
      #         storage: 1Gi
      volumeClaimTemplates:
      - metadata:
          name: config
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "local-path"
          resources:
            requests:
              storage: 1Gi
      volumeClaimTemplates:
      - metadata:
          name: sync
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "local-path"
          resources:
            requests:
              storage: 1Gi