apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snipeit
  namespace: snipeit
spec:
  chart:
    spec:
      chart: polymorphic-app
      reconcileStrategy: ChartVersion
      version: 1.2.8
      sourceRef:
        kind: HelmRepository
        name: polymorphic-app #Edited the name from polymorphic to polymorphic-app
        namespace: snipeit #Edited the namespace from flux-system to snipeit
  interval: 1m0s
  values:
    services:
      - name: mariadb
        type: StatefulSet
        image: 
          # repository: mariadb #commented to get an error and get alerts in the mattermost
          repository: wqwjdoiqj
          tag: 10.6
        # command: ["mysqld", "--innodb-file-per-table=1", "--lower-case-table-names=0", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_c"]
        healthcheck:
          enabled: false
        env:
          - name: TZ
            value: "Asia/Kolkata"
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "yes"
          - name: MYSQL_DATABASE
            value: "snipeit"
          - name: MYSQL_USER
            value: "snipeit"
          - name: MYSQL_PASSWORD
            value: "987654321" # set your own password
        volumeMounts: 
          - name: mysql
            mountPath: /var/lib/mysql
        volumes:
          - name: mysql # need to create PVC for it
            persistentVolumeClaim:
              claimName: mysql-pvc
        service:
          enabled: true
          type: ClusterIP
          ports:
          - port: 3306
            targetPort: mysql
            name:  mysql
        ports:
          - name: mysql
            containerPort: 3306
      - name: snipeit
        type: Deployment
        image: 
          repository: lscr.io/linuxserver/snipe-it
          tag: 6.3.0
        healthcheck:
          enabled: false
        env:
          - name: MYSQL_PORT_3306_TCP_ADDR
            value: "snipeit-mariadb-svc"
          - name: MYSQL_PORT_3306_TCP_PORT
            value: "3306"
          - name: APP_URL
            value: "http://imp-snipeit.com" # give your own URL
          - name: APP_KEY
            value: "base64:ooV4cyqX7rqCpQj9NhTDCScE2MjqxYx1qkRj2HfdnK8="
          - name: MYSQL_DATABASE
            value: "snipeit"
          - name: MYSQL_USER
            value: "snipeit"
          - name: MYSQL_PASSWORD
            value: "987654321" # set your own password
          - name: TZ
            value: "Asia/kolkata"
          - name: APP_ENV
            value: "production"
          - name: APP_DEBUG
            value: "false" #Set to true to check the logs
          - name: MAIL_DRIVER
            value: "log"
          # - name: MAIL_PORT_587_TCP_ADDR
          #   value: ""
          # - name: MAIL_PORT_587_TCP_PORT
          #   value: ""
          # - name: MAIL_ENV_USERNAME
          #   value: ""
          # - name: MAIL_ENV_PASSWORD
          #   value: ""
          - name: MAIL_ENV_FROM_ADDR
            value: ""
          - name: MAIL_ENV_FROM_NAME
            value: "Snipe-IT"
          - name: MAIL_ENV_ENCRYPTION
            value: "tls"
        volumeMounts: 
          - name: snipeit
            mountPath: /config
        volumes:
          - name: snipeit # need to creat PVC for it
            persistentVolumeClaim:
              claimName: snipeit-pvc

        service:
          enabled: true
          type: ClusterIP
          ports:
          - port: 80
            targetPort: snipeit
            name:  snipeit
        ingress:
          enabled: true
          className: "nginx"
          hosts:
            - host: imp-snipeit.com # give your own
              paths:
              - path: /
                pathType: Prefix
                servicePort: 80
                serviceName: snipeit #added
        ports:
          - name: snipeit
            containerPort: 80