apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: job-app
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit: 
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: | 
        Perform automatic image update
      # messageTemplate: "{{range .updatedImages}}{{println .}}{{end}}"
      # messageTemplate: |
      #   {{- range .updatedImages -}}
      #   {{ . }}
      #   {{- end -}}      
    push:
      branch: main
  update:
    path: ./infastructure/base/job-app/release.yaml
    strategy: Setters
    updatedImages: ["{{ .repository }}:{{ .tag }}"]