apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: job-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: job-app
  filterTags:
    pattern: "ci-.*-(\\d+)"
    extract: $1   
  policy:
    numerical:
      order: desc
      # range: "*"   # Fetch images across all available tags
      # extract: $(tag | split('-') | last)  # Extract the last part of the tag after splitting by '-'


      # strategy: highest
      # range: "*"
      # extract: $(tag | split('-') | index 2)



    # rules:
    #   - regex:
    #       pattern: "ci-.*-(\\d+)"  # Regex to capture the epoch timestamp part
    #       extract: "tag"  # Extract the entire tag for use in updates


    # numerical:
    #   order: asc
    #   strategy: highest
    #   range: "*"
    #   extract: $(tag | split '-' | last)

    #   extract: $(tag | regex '^.*-(\\d+)$' | groups[1])

    #   extract: $(tag | split('-') | index 2)


