apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: my-mysql
  namespace: demo-flux
spec:
  chart:
    spec:
      chart: mysql
      version: 1.6.9
      interval: 5h # this is for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: mysql-repo
  releaseName: my-mysql
  targetNamespace: demo-flux
  interval: 1h # this is for drifting of the helm created resources
  values:
    fullnameOverride: my-mysql
    mysqlRootPassword: "12345678"
    mysqlUser: test 
    mysqlPassword: test123
    mysqlDatabase: apply