# flux HelmRelease crd for installing nginx ingress controller helm chart
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: job-app
  namespace: demo-flux
spec:
  chart:
    spec:
      chart: polymorphic-app
      version: 2.1.1
      interval: 5h # this is for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: polymorphic-app
  releaseName: job-app
  targetNamespace: demo-flux
  interval: 1h # this is for drifting of the helm created resources
  values:
    nameOverride: ""
    fullnameOverride: ""
    prefixWithReleaseName:
      enabled: true
    image:
      repository: chandanteekinavar/docker-exercise-app
      # tag: "ci-11f6ef4-1722422386"
      # tag:  # {"$imagepolicy": "flux-system:job-app"}
      imagePolicy:
        fluxSystem: job-app
      pullPolicy: IfNotPresent

    env:
      - name: DB_HOST
        value: "my-mysql"
      - name: DB_PORT
        value: "3306"  
      - name: DB_DATABASE
        value: "apply"
      - name: DB_USERNAME
        value: "root"
      - name: DB_PASSWORD
        value: "12345678"


    services:
      - name: job
        image:
        averageUtilization: 50

        healthcheck:
          enabled: false
          type: httpGet



        autoscaling: false
        minReplicaCount: 1
        maxReplicaCount: 1
        env: []
        envFrom: []
        command: ["sh", "-c", "npm run dev && php artisan serve --host=0.0.0.0 --port=8000"]
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP


        service:
          enabled: true
          # className: nginx
          type: ClusterIP
          ports:
          - name: http
            port: 80
            targetPort: 8000
            protocol: TCP
          annotations: {}
              
        ingress:
          enabled: true
          annotations: {}
          hosts:
            - host: job-app.com
              paths:
                - path: "/"
                  pathType: Prefix
                  serviceName: http
                  servicePort: 80



    jobs:
      - name: migrate
        image: 
          repository: chandanteekinavar/docker-exercise-app
          tag: "2.0"
          annotations: 
            "helm.sh/hook": pre-install
            "helm.sh/hook-weight": "0"
            "helm.sh/hook-delete-policy": hook-succeeded
          command: ["sh", "-c", "php artisan migrate:refresh && php artisan db:seed"]